# Generated by Django 5.2.8 on 2025-11-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
